server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_bank?createDatabaseIfNotExist=true
    username: root
    password: fifa2014

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true